layout: sidebar
style: light
masthead_style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

include:
  - "_img"
  - "_files"
  - "_scripts"

user: # Override GitHub metadata
  avatar_url: ./_img/avatar.jpeg
  casual_name: Peter Tse
  name: TSE Ho Nam (Peter)
  bio: "Deep Learning | Robotics | Software Development<br>An engineer with theoretical background."
  description: "Deep Learning | Robotics | Software Development - An engineer with theoretical background."
  email: hntse@connect.ust.hk

experience:
  - title: Machine Learning Engineer
    content: Dayta AI · Intern
    date: Oct 2018 - Feb 2019
    location: Hong Kong
    icon: dayta-icon.jpeg
    expand: dayta-supp
    supp: <p>I worked on multiple projects involving deep learning and computer vision. The first was to package an existing eye gaze detection model into production, which was planned to help on e-sports training. The second was to develop a model that detects if a person falls. It was based on 3D pose estimation and was planned to be used in nursery homes. I was also involved in other smaller projects on anomaly detection and Chinese paraphrasing.</p><p>Despite taking a lot of theoretical courses in machine learning, I had only done machine projects as in course assignments. Working in Dayta gave me real life problems to solve using the techniques I learnt in class. I also learnt a lot of practical stuff when I interned there, for example on how concurrency works in Python, and how to dockerise a neural model. I also learnt a bit on business operation from the founders and got to exchange ideas with my colleagues, whom some are Masters students. It was a fruitful experience.</p>
  - title: Student Researcher
    content: Hong Kong University of Science and Technology
    date: Jun 2018 - Aug 2018
    location: Hong Kong
    icon: ust-icon.png
    expand: hkust-research-supp
    supp: <p>We conducted an industrial research project sponsored by AECOM, which aimed to improve the existing Hong Kong Air Ventilation Assessment using data-driven approaches. The research report is available <a href="_files/RIPS-HK2018.pdf">here</a> and I was mainly responsible for section 3. We are currently proceeding further with our research and running more experiments, and we hope to publish a paper on this matter soon.</p><p>This is my first time conducting a proper research. It was kind of stressful to brainstorm new ideas to solve the problem, especially in the limited time of 2 months, but it was a lot of fun. Some of my partners were from the U.S. and we were able to exchange on ideas, knowledge and even culture. We even had a Macau trip together and that was very memorable.</p>
  - title: Senior Member
    content: HKUST Robotics Team
    date: Oct 2016 - Aug 2018
    location: Hong Kong
    icon: robo-icon.png
    expand: robo-supp
    supp: <p>We participated in a nation-wide autonomous car racing competition and was awarded Third Class Honour. We also trained new members by holding tutorials on topics in robotics and software engineering. We conducted R&D, such as developing new IC and component library and developing new internal software for training/productivity purposes (more details in 'Projects'). We also hosted STEM competitions for primary and secondary students, and provided guidance to them throughout.</p><p>This is easily the most memorable experience in my university life. I learnt a lot throughout this journey. All my basic software engineering skills are picked up here, along with other skills like soldering and 3D parts designing/printing. I also had the privilege to interview and teach new members and it was very fun. Conflicts happened here and there, and while they are not pleasant to deal with, they are important experiences to me. Frankly, I am very grateful that I am able to be a part of the team.</p>

education:
  - title: Hong Kong University of Science and Technology
    content: Bachelor of Science in Computer Science and Mathematics
    date: Sep 2016 - Jun 2020
    location: Hong Kong
    icon: ust-icon.png
    expand: hkust-grade
    courses:
      - title: Introduction to Computer Science
        code: COMP 1021
        grade: A+
      - title: Honors OOP and Data Structures
        code: COMP 2012H
        grade: A+
      - title: Computer Organization
        code: COMP 2611
        grade: A
      - title: Honors Discrete Mathematics
        code: COMP 2711H
        grade: A+
      - title: Honors Software Engineering
        code: COMP 3111H
        grade: A+
      - title: Deep Learning for Computer Vision
        code: COMP 4901J
        grade: A+
      - title: Cloud Computing and Big Data Systems
        code: COMP 4651
        grade: A+
      - title: Foundations of Computer Vision
        code: COMP 4901L
        grade: A+
      - title: Introduction to Advanced Algorithmic Techniques
        code: COMP 5711
        grade: A+
      - title: Calculus IB
        code: MATH 1013
        grade: A
      - title: Calculus II
        code: MATH 1014
        grade: A+
      - title: Matrix Algebra and Applications
        code: MATH 2111
        grade: A+
      - title: Multivariable Calculus
        code: MATH 2023
        grade: A+
      - title: Mathematical Analysis
        code: MATH 2033
        grade: A
      - title: Applied Statistics
        code: MATH 2411
        grade: A+
      - title: Probability
        code: MATH 2421
        grade: A+
      - title: Real Analysis
        code: MATH 3033
        grade: A+
      - title: Abstract Algebra
        code: MATH 3121
        grade: A+
      - title: Matrix Computation
        code: MATH 3322
        grade: A
      - title: Data Analytic Tools
        code: MATH 3332
        grade: A+
      - title: Combinatorial Analysis
        code: MATH 3343
        grade: A+
      - title: Machine Learning for Natural Language Processing
        code: MATH 4824B
        grade: A+

  - title: ETH Zürich
    content: Exchange Student in Departement Informatik
    date: Feb 2019 - Aug 2019
    location: Switzerland
    icon: eth-icon.png
    expand: eth-grade
    courses:
      - title: Statistical Learning Theory
        code: 252-0526-00
        grade: 5.5/6
      - title: Autonomous Mobile Robots
        code: 151-0854-00
        grade: 5.75/6
      - title: System Software and Distributed Systems
        code: MOB-001
        grade: 5.25/6

projects:
  - section: Course Projects
    repos:
      [
        cs231n,
        COMP4901K,
        serverless-smart-album,
        COMP4901L,
        stat-learning,
        amr-vrep,
        nlu-nlm,
        nlu-story,
      ]
  - section: Robotics Team
    repos: [Chasing17, libsccc, tutorials, judge, kea128, nfc-pos]
  - section: Competitions
    repos: [MSxDJI, CodeIT-2018, ProcalParsing]
  - section: Side Projects
    repos:
      [
        quota-track,
        tg-reminder-bot,
        visited-map,
        mcreng.github.io,
        url-shortener,
        quick-todo,
      ]

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: mcreng
  hackerrank: mcreng
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

skills:
  - section: Generic
    details:
      - name: Python
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
        description: Fluent
      - name: C++
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/cpp/cpp.png
        description: Fluent
      - name: Javascript
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png
        description: Fluent
      - name: Java
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png
        description: Moderate
      - name: git
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png
        description: Fluent
      - name: Markdown
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/markdown/markdown.png
        description: Fluent
      - name: LaTex
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/latex/latex.png
        description: Fluent
      - name: Ubuntu
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ubuntu/ubuntu.png
        description: Daily OS

  - section: Machine Learning/Data Analytics
    details:
      - name: Jupyter
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/jupyter-notebook/jupyter-notebook.png
        description: Fluent
      - name: TensorFlow
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/tensorflow/tensorflow.png
        description: Fluent
      - name: Keras
        image_url: https://avatars2.githubusercontent.com/u/34455048?s=200&v=4
        description: Fluent
      - name: sklearn
        image_url: https://avatars2.githubusercontent.com/u/365630?s=200&v=4
        description: Fluent
      - name: OpenCV
        image_url: https://avatars1.githubusercontent.com/u/5009934?s=200&v=4
        description: Fluent
      - name: NLTK
        image_url: https://avatars1.githubusercontent.com/u/124114?s=200&v=4
        description: Fluent
      - name: NumPy
        image_url: https://avatars3.githubusercontent.com/u/288276?s=200&v=4
        description: Fluent
      - name: Pandas
        image_url: https://avatars1.githubusercontent.com/u/21206976?s=200&v=4
        description: Fluent
      - name: Matplotlib
        image_url: https://avatars0.githubusercontent.com/u/215947?s=200&v=4
        description: Fluent
      - name: PyTorch
        image_url: https://avatars0.githubusercontent.com/u/21003710?s=200&v=4
        description: Moderate
      - name: SQL
        image_url: https://cdn4.iconfinder.com/data/icons/flat-pro-database-set-1/32/sql-badge-512.png
        description: Moderate
      - name: MATLAB
        image_url: https://avatars0.githubusercontent.com/u/8590076?s=200&v=4
        description: Moderate

  - section: Cloud Computing/Big Data
    details:
      - name: Spark
        image_url: https://www.vectorlogo.zone/logos/apache_spark/apache_spark-icon.svg
        description: Fluent
      - name: Hadoop
        image_url: https://hadoop.apache.org/elephant.png
        description: Fluent
      - name: Docker
        image_url: https://avatars0.githubusercontent.com/u/5429470?s=200&v=4
        description: Moderate
      - name: OpenFaaS
        image_url: https://avatars0.githubusercontent.com/u/27013154?s=200&v=4
        description: Moderate
      - name: Kubernetes
        image_url: https://avatars3.githubusercontent.com/u/13629408?s=200&v=4
        description: Moderate
      - name: AWS
        image_url: https://avatars0.githubusercontent.com/u/2232217?s=200&v=4
        description: Moderate
      - name: Azure
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/azure/azure.png
        description: Moderate

  - section: Parallel Programming
    details:
      - name: pthreads
        description: Learning in class
      - name: OpenMP
        image_url: https://avatars2.githubusercontent.com/u/8496952?s=200&v=4
        description: Learning in class
      - name: Open MPI
        image_url: https://avatars0.githubusercontent.com/u/2165682?s=200&v=4
        description: Learning in class
      - name: CUDA
        image_url: https://avatars2.githubusercontent.com/u/1728152?s=200&v=4
        description: Learning in class

  - section: Web Development
    details:
      - name: MongoDB
        image_url: https://avatars1.githubusercontent.com/u/45120?s=200&v=4
        description: Moderate
      - name: ExpressJS
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/express/express.png
        description: Moderate
      - name: ReactJS
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png
        description: Moderate
      - name: NodeJS
        image_url: https://avatars3.githubusercontent.com/u/9950313?s=200&v=4
        description: Moderate
      - name: Bootstrap
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/bootstrap/bootstrap.png
        description: Moderate
      - name: jQuery
        image_url: https://avatars0.githubusercontent.com/u/70142?s=200&v=4
        description: Moderate
      - name: Flask
        image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/flask/flask.png
        description: Moderate
      - name: Redis
        image_url: https://cdn.worldvectorlogo.com/logos/redis.svg
        description: Moderate
      - name: Firebase
        image_url: https://avatars2.githubusercontent.com/u/1335026?s=200&v=4
        description: Moderate
      - name: Heroku
        image_url: https://avatars3.githubusercontent.com/u/23211?s=200&v=4
        description: Moderate

  - section: Robotics/Embedded System
    details:
      - name: Arduino
        image_url: https://avatars2.githubusercontent.com/u/379109?s=200&v=4
        description: Fluent
      - name: Raspberry Pi
        image_url: https://avatars2.githubusercontent.com/u/1294177?s=200&v=4
        description: Fluent
      - name: NXP K60 & KEA
        image_url: https://avatars1.githubusercontent.com/u/15616545?s=200&v=4
        description: Fluent
      - name: STM32
        image_url: https://avatars0.githubusercontent.com/u/12180191?s=200&v=4
        description: Moderate
