layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

include:
  - "_img"
  - "_files"

# defaults:
#   - scope:
#       path: "" # an empty string here means all files in the project
#       type: "posts"
#     values:
#       layout: "post"

experience:
  - title: Machine Learning Engineer
    content: Dayta AI · Intern
    date: Oct 2018 - Feb 2019
    location: Hong Kong
    icon: dayta-icon.jpeg
    expand: dayta-supp
    supp: <p>I worked on multiple projects involving deep learning and computer vision. The first was to package an existing eye gaze detection model into production, which was planned to help on e-sports training. The second was to develop a model that detects if a person falls. It was based on 3D pose estimation and was planned to be used in nursery homes. I was also involved in other smaller projects on anomaly detection and Chinese paraphrasing.</p>
  - title: Student Researcher
    content: Hong Kong University of Science and Technology
    date: Jun 2018 - Aug 2018
    location: Hong Kong
    icon: ust-icon.png
    expand: hkust-research-supp
    supp: <p>We conducted an industrial research project sponsored by AECOM, which aimed to improve the existing Hong Kong Air Ventilation Assessment using data-driven approaches. The research report is available <a href="_files/RIPS-HK2018.pdf">here</a> and I was mainly responsible for section 3. We are currently proceeding further with our research and running more experiments, and we hope to publish a paper on this matter soon.</p>
  - title: Senior Member
    content: HKUST Robotics Team
    date: Oct 2016 - Aug 2018
    location: Hong Kong
    icon: robo-icon.png
    expand: robo-supp
    supp: <p>We participated in a nation-wide autonomous car racing competition and was awarded Third Class Honour. We also trained new members by holding tutorials on topics in robotics and software engineering. We conducted R&D, such as developing new IC and component library and developing new internal software for training/productivity purposes (more details in 'Projects'). We also hosted STEM competitions for primary and secondary students, and provided guidance to them throughout.</p>

education:
  - title: Hong Kong University of Science and Technology
    content: Bachelor of Science in Computer Science and Mathematics
    date: Sep 2016 - Jun 2020
    location: Hong Kong
    icon: ust-icon.png
    expand: hkust-grade
    courses:
      - title: Honors Design and Analysis of Algorithms
        code: COMP 3711H
        grade: A+
      - title: Honors OOP and Data Structures
        code: COMP 2012H
        grade: A+
      - title: Honors Discrete Mathematics
        code: COMP 2711H
        grade: A+
      - title: Mathematical Analysis
        code: MATH 2033
        grade: A
      - title: Applied Statistics
        code: MATH 2411
        grade: A+
      - title: Probability
        code: MATH 2421
        grade: A+
      - title: Matrix Computation
        code: MATH 3322
        grade: A
      - title: Combinotorial Analysis
        code: MATH 3343
        grade: A+
      - title: Honors Software Engineering
        code: COMP 3111H
        grade: A+
      - title: Deep Learning for Computer Vision
        code: COMP 4901J
        grade: A+
      - title: Machine Learning for Natural Language Processing
        code: MATH 4824B
        grade: A+
      - title: Real Analysis
        code: MATH 3033
        grade: A+
      - title: Data Analytic Tools
        code: MATH 3332
        grade: A+
      - title: Cloud Computing and Big Data Systems
        code: MATH 4651
        grade: --
      - title: Foundations of Computer Vision
        code: COMP 4901L
        grade: --
      - title: Introduction to Advanced Algorithmic Techniques
        code: COMP 5711
        grade: --
  - title: ETH Zürich
    content: Exchange Student in Departement Informatik
    date: Feb 2019 - Aug 2019
    location: Switzerland
    icon: eth-icon.png
    expand: eth-grade
    courses:
      - title: Statistical Learning Theory
        code: 252-0526-00
        grade: 5.5
      - title: Autonomous Mobile Robots
        code: 151-0854-00
        grade: 5.75

# projects:
#   sort_by: pushed
#   # sort_by options:
#   #   - pushed
#   #   - stars
#   limit: 9
#   exclude:
#     archived: false
#     forks: true
#     projects:
#     # - repo-name

# social_media:
# behance: your_username
# dribbble: your_username
# facebook: your_username
# hackerrank: your_username
# instagram: your_username
# keybase: your_username
# linkedin: your_username
# mastodon: your_username
# medium: your_username
# stackoverflow: your_user_id
# telegram: your_username
# twitter: your_username
# unsplash: your_username
# vk: your_username
# website: http://your_website_url
# youtube: your_username

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
